services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend

    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/saas
      JWT_SECRET: supersecretkey
      BASE_DOMAIN: localhost
      PORT: 3000
    depends_on:
      - db

  frontend:
    build: ./frontend

    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    depends_on:
      - backend

networks:
  saas-network:
    driver: bridge

volumes:
  pgdata:
